### ISSUE TITLE
WFCatalog HTTP 413 when end date is in the future

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/mediatorws#119]
Hi,

Just a small "improvement" idea. When using WFCatalog methods with end date set in the future, HTTP 413 is returned.

Example (executed on 26-06-2020):

Direct WFCatalog request at ETHZ (200: OK):
http://eida.ethz.ch/eidaws/wfcatalog/1/query?include=sample&net=CH&sta=NALPS&start=2020-06-01&end=2020-08-01&cha=HG?,?H?,?DF

Same request via Federator (Error 413: Request too large):
http://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?include=sample&net=CH&sta=NALPS&start=2020-06-01&end=2020-08-01&cha=HG?,?H?,?DF

Cheers,
Jarek

**Comment by damb** [comment]
@jbienkowski, sorry for the delayed response.

The issue occurred due to a bug when executing endpoint requests by means of the HTTP POST method. Requesting `eidaws-wfcatalog` data via HTTP POST is necessary since most of the DCs did not deploy the most recent version of [EIDA/wfcatalog](https://github.com/EIDA/wfcatalog), yet.

It should be fixed with the most recent deployment.

Thanks again for the catch, @jbienkowski.
