### ISSUE TITLE
Station required or 400 Bad Request returned

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#4]
Hi guys, why is this a bad request:

    http://mediator-devel.ethz.ch/fdsnws/dataselect/1/query?net=NL&start=2016-01-01T00:00:00&end=2016-01-01T00:01:00

but when I give it a station the response is fine (albeit incomplete):

    http://mediator-devel.ethz.ch/fdsnws/dataselect/1/query?net=NL&sta=HGN&start=2016-01-01T00:00:00&end=2016-01-01T00:01:00

Best,
Mathijs

**Comment by feuchner** [comment]
BadRequest for the first request (without station) was caused by an error in the code. Note that the same query against the ODC service yields error 413: Request Entity Too Large. This should be propagated by the federator, which is currently not the case (federator yields a 204, to be fixed). The second query (with station HGN) yields now the same result as a direct query to the ODC node.

**Comment by Jollyfant** [comment]
Ok nice!

**Comment by damb** [comment]
Seems to work with the most recent code. Closed.
