### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#52]
Hi, can we get the Dockerfile too instead of just the image. It will be easier to do some logging configuration since we want to write to a file and mount it outside the container for ingestion in ELK.

**Comment by damb** [comment]
Hi @Jollyfant,

as I mentioned already in https://github.com/EIDA/mediatorws/issues/37#issuecomment-406995148 I did not generate the image with a `Dockerfile`. Instead I used `ansible-container` since this was easier for me. Hence, there are playbooks but no `Dockerfile`.

However, I understand what you'd like to accomplish. So either *you* write a `Dockerfile` or you are going to work based on the playbooks. Let me know if you need them.

**Comment by Jollyfant** [comment]
Ok I will reopen https://github.com/EIDA/mediatorws/pull/38
